#FILE kscao_lgs.conf
# Keck SCAO LGS circa 2023 (pre-KAPA)

__reset__         		#replace all previous entries.
__default__	      		#this file contains default setup.

#defines simulation parameters.
include     	= "keck_sim.conf"

#AO type. 
include     	= "keck_dm_single.conf" 

#Atmospheric profile
include     	= "atm_mk13n50p_ground_detail.conf" #Mauna Kea 13N, Chun MK_OTP 'binned' model

#Wavefront sensor information. 
include     	= "keck_wfs_lgs_strap_lbwfs.conf"

#Including configurations for reconstruction (tomo/fitting)
include     	= "recon.conf"

#For debugging purpose
include     	= "keck_dbg.conf"

#For DM fitting
include		= "fit_oa.conf"

#### Overrides
#Set LGS and TT sensor location

sim.zadeg     = 30    #zenith angle. moved from atm.zadeg

# Grid of PSFs
# evl.thetax  	= [-1 -1 -1  0  0  0  1  1  1]
# evl.thetay  	= [-1  0  1 -1  0  1 -1  0  1]
# evl.fov		= 10	# this value in arcsec will scale the evl points

# Single PSF
evl.thetax=[0  0  0  0  0  0  0  0  5  5  5  5  5  5  5  5 10 10 10 10 10 10 10 10  15 15 15 15 15 15 15 15 20 20 20 20 20 20 20 20 25 25 25 25 25 25 25 25 30 30 30 30 30 30 30 30 35 35 35 35 35 35 35 35]
evl.thetay=[0  5 10 15 20 25 30 35  0  5 10 15 20 25 30 35  0  5 10 15 20 25 30 35   0  5 10 15 20 25 30 35  0  5 10 15 20 25 30 35  0  5 10 15 20 25 30 35  0  5 10 15 20 25 30 35  0  5 10 15 20 25 30 35]
evl.fov		= 1	# this value in arcsec will scale the evl points
evl.psfsize = [256 256 256 256 256 256 256 256 256]
evl.wvl     = [0.432e-6 0.544e-6 0.652e-6 0.810e-6 0.877e-6 1.020e-6 1.248e-6 1.673e-6 2.200e-6]

# Tweak some evaluation parameters
evl.psf		= [1]
evl.wt		= [1]
evl.dx		= 1/64 #1/32 is needed to have enough size for short wavelength

# Tweak some reconstruction parameters relative to MAOS base.
recon.alg	= 0 #scao mvr works better than lsr; 0 = min var, 1 = least squares
recon.split	= 0

sim.end       = 1500  #last time step (exclusive)
sim.seeds     = [0]

