#FILE kscao_lgs.conf
# Keck SCAO LGS circa 2023 (pre-KAPA)

__reset__         		#replace all previous entries.
__default__	      		#this file contains default setup.

#defines simulation parameters.
include     	= "keck_sim.conf"

#AO type. 
include     	= "keck_dm_single.conf" 

#Atmospheric profile
include     	= "atm_mk13n50p_ground_detail.conf" #Mauna Kea 13N, Chun MK_OTP 'binned' model

#Wavefront sensor information. 
include     	= "keck_wfs_1lgs_strap_lbwfs.conf" # 3 types of WFSs, 1 LGS WFS, 1 TT, 1 LBWFS

#Including configurations for reconstruction (tomo/fitting)
include     	= "recon.conf"

#For debugging purpose
include     	= "dbg.conf"

#For DM fitting
include		= "fit_oa.conf"

#### Overrides
include		= "kapa_compare_sky_evl.conf"

atm.wdrand = 0 # We provide the wind direction, so don't randomize it

# Tweak some reconstruction parameters relative to MAOS base.
recon.alg	= 0 #scao mvr works better than lsr; 0 = min var, 1 = least squares
recon.split	= 0

#sim.end       = 600  #last time step (exclusive)
