#FILE kapa_compare_sky_evl.conf
# Evaluation parameters for KAPA simulations (comparing to on-sky data)

# Grid of PSFs
# 19 total. 13 having x range from -12->12 by 2s while y stays at 0. 6 having x stay at 0 and y range from 2->12 (already did 0,0)
evl.thetax=[-12 -10 -8 -6 -4 -2 0 2 4 6 8 10 12 0 0 0 0 0  0 ]
evl.thetay=[0   0   0  0  0  0  0 0 0 0 0 0  0  2 4 6 8 10 12]
evl.fov		= 1	# this value in arcsec will scale the evl points
evl.psfsize = [?] * 4 # TODO: determine apprpriate psfsize for each wvl
# evl.wvl     = [0.432e-6 0.544e-6 0.652e-6 0.810e-6 0.877e-6 1.020e-6 1.248e-6 1.673e-6 2.200e-6] # TODO Decide if we want all of these
evl.wvl = [1.0251e-6 1.2429e-6 1.6383e-6 2.1145e-6] # Y, J, Hbb, Kp https://www2.keck.hawaii.edu/inst/osiris/technical/filters/filter_index.html

# Tweak some evaluation parameters
evl.psf		= [1]
evl.wt		= [1]
evl.dx		= 1/64 #1/32 is needed to have enough size for short wavelength