#FILE keck_wfs_4lgs_strap_lbwfs.conf
# Dummy template
include=good_powfs_none.conf

# LGS fast Shack-Hartmann WFS
include=keck_shwfs_4lgs.conf

# NGS fast tip-tilt and focus WFS
include=keck_shwfs_tt_strap.conf

# NGS slow, high-order truth sensor.
include=keck_shwfs_twfs_lbwfs.conf


