#File llt_CLk.conf for center launch
#Usage: powfs.fnllt=[llt_CL.conf,,]
#Specifying laser launch telescope and sodium layer parameters.

include=keck_llt_CL.conf

# JLU> I don't think this is quite right as laser is assumed to be launched at 3.1 m out from
# center of the primary mirror. But how else can we do a center launch laser constellation? 
#llt.ox     =[-7.6 0 0 7.6] * 0.44   # LLT x coordinate in meters relative to primary. 
#llt.oy     =[0 7.6 -7.6 0] * 0.44   # LLT y coordinate. note 0.44 = 90km * 1/206265.
# Should these all instead be 0?
llt.ox     =[0 0 0 0] * 0.44   # LLT x coordinate in meters relative to primary. 
llt.oy     =[0 0 0 0] * 0.44   # LLT y coordinate. note 0.44 = 90km * 1/206265.
