#FILE keck_wfs_lgs_ttf.conf
# Dummy template
include=/u/nstieg/work/ao/keck/maos/keck_maos/kapa/powfs_none.conf

# LGS fast Shack-Hartmann WFS
include=keck_shwfs_lgs.conf

# NGS fast tip-tilt and focus WFS
include=keck_shwfs_ttf_strap.conf

# NGS slow, high-order truth sensor.
include=keck_shwfs_twfs_lbwfs.conf


