#FILE A_klear_master.conf
# 2026: STRATA = KAPA + K1AOF (ASM + S-LGS Asterism)

__reset__         		#replace all previous entries.
__default__	      		#this file contains default setup.

#add the directory to search path for files. Relative to $MAOS_CONFIG
path = "bin"
path = "atm"

#defines simulation parameters.
include     	= "keck_sim.conf"

#AO type (mirrors). 
include     	= "keck_ASM.conf" # ASM-only (NOT multi-conjugate)

#Atmospheric profile
include     	= "atm_mk13n50p_ground_detail.conf" #Mauna Kea 13N, Chun MK_OTP 'binned' model

#Wavefront sensor information. 
include     	= "keck_wfs_all.conf" # LGSWFS, TTWFS, LBWFS

#Including configurations for reconstruction (tomo/fitting)
include     	= "keck_recon.conf"

#For debugging purpose
include     	= "keck_dbg.conf"

#For DM fitting
include		= "fit_oa.conf"


### ---- STRATA OVERRIDES ---- ###

# Need to double check with Jessica 
# powfs.rne   = [0.1 11.188 1] # what I had written down
powfs.rne   =  [0.5 0.1 1.0] # what I am running with

### 
# 10 PSFs (9 wavelengths)
###
evl.psfsize = [512]
evl.wvl = [0.432e-6 0.544e-6 0.652e-6 0.810e-6 0.877e-6 1.020e-6 1.248e-6 1.673e-6 2.200e-6]
evl.thetax  = [0 5 10 15 20 25 30 35 45 60]
evl.thetay  = [0 0 0 0 0 0 0 0 0 0]

####
# 4x30watt LGS (8mag TT)
# 30W LGS is 7.66 mag
# Actuator Count: 2925
####
dm.dx = [0.18] # As of STRATA meeting 04/16/26
powfs.siglev = [51.566 42387.592 41.558]
powfs.bkgrnd = [0.1 1.056 0.001]
powfs.nearecon = [211.408 0.269 202.516]

####
# LGS asterism (17")
# NGS asterism (0")
# TRUTH asterism (0")
####
powfs.nwfs = [4 1 1]
powfs0_llt.ox = [1 0 -1 0]*6.5
powfs0_llt.oy = [0 1 0 -1]*6.5
wfs.thetax = [17 0 -17 0 0 0]
wfs.thetay = [0 17 0 -17 0 0]

####
# Weird Overrides
####
powfs.dtrat = [1 1 1000000]
powfs.misregx = [0.05 0 0.42]
powfs.misregy = [0.05 0 0.42]
powfs.rne = [0.1 11.188 1] # For KOLA consistency reasons (but probably should be fixed.....)

# Extra?
evl.fov		= 1	# this value in arcsec will scale the evl points
evl.psf		= [1]
evl.wt		= [1]
