#FILE keck_wfs_lgs_ttf.conf
# Dummy template
include=good_powfs_none.conf

# LGS fast Shack-Hartmann WFS
include=keck_shwfs_ocam2k_slgs.conf

# NGS fast tip-tilt WFS
include=keck_shwfs_tt_strap.conf

# NGS slow, high-order truth sensor
include=keck_shwfs_twfs_lbwfs.conf
