#FILE keck_wfs_lgs_ttf.conf
# Dummy template
include=good_powfs_none.conf

# LGS fast Shack-Hartmann WFS
include=keck_shwfs_ocam2k_slgs.conf

# NGS fast tip-tilt WFS
include=keck_shwfs_tt_strap.conf

# NGS slow, high-order truth sensor. Also used for focus. We define 
# a separate LBWFS for focus control because we usually wait for it to
# converge before we start observing. If we don't, then we don't have
# focus control, so we kind of 'hack' the simulation by having a separate
# one which just does focus control
include=keck_shwfs_twfs_lbwfs.conf
include=keck_shwfs_twfs_lbwfs_focus.conf